services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - mariadb
      - mongodb
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development

  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - ./auth_service:/usr/src/app
    environment:
        TEST_USER_NAME: ${TEST_USER_NAME}
        TEST_USER_PASSWORD: ${TEST_USER_PASSWORD}
        PYTHONUNBUFFERED: 1
        SECRET_KEY: ${SECRET_KEY}



  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mariadb-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    command:
      - --auth
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  backend:
    build: ./backend
    ports:
      - "8002:8002"
    depends_on:
      - auth-service
      - mariadb
      - mongodb
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - MONGO_URI=${MONGO_URI}


  analytics-service:
    build: ./analytics_service
    ports:
      - "8003:8003"
    depends_on:
      - mariadb
      - mongodb
    networks:
      - app-network
    volumes:
      - ./analytics_service:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_HOST=mariadb
      - MYSQL_DB=app_db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MONGO_URI=${MONGO_URI}
    command: [ "python", "analytics_service.py" ]

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
  mongodb-data: