apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: 273354625202.dkr.ecr.us-east-2.amazonaws.com/myapp/analytics:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_DB
              value: "app_db"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
          command: ["python", "analytics_service.py"]
