apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SECRET_KEY
        - name: TEST_USER_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TEST_USER_NAME
        - name: TEST_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TEST_USER_PASSWORD